### PR TITLE
feat: add contributors

### PR DESCRIPTION
**Pull request by xiaolou86**
Resolves https://github.com/starknet-io/starknet-docs/issues/1042

### CODE REVIEW

**Comment by stoobie** [comment]
@xiaolou86 Can you tell me the source of your code? Did you write it yourself or is from another open source project? Before we can use it, I need to make sure we're allowed to use it.

**Comment by xiaolou86** [comment]
@stoobie I write it myself, and something assisted by GPT because I am not good at css and html. So feel free to use anywhere.

**Comment by stoobie** [comment]
@xiaolou86 Ok. Thanks for letting me know. I've sent it for code review.

**Comment by stoobie** [comment]
@xiaolou86 a few comments:

* Can you make the corners of the contributors box and the buttons curved so that they match the style of the tables?
image

  Here's a table corner:
  image

* Can you make each contributor's name be vertically aligned with the center of their avatar instead of the bottom?
* Can the text in the header match the look of the breadcrumb text?
image

**Comment by xiaolou86** [comment]
> a few comments:
> 
> * Can you make the corners of the contributors box and the buttons curved so that they match the style of the tables?
>   image
>   Here's a table corner:
>   image

@stoobie 
Done.

> * Can you make each contributor's name be vertically aligned with the center of their avatar instead of the bottom?

Done.

> * Can the text in the header match the look of the breadcrumb text?
>   image

Done.

**Review by lotem-starkware — APPROVED** [review]
looks good

**Comment by stoobie** [comment]
@xiaolou86 Could you please remove the ui-bundle.zip file? I'll rebuild it after the changes are merged to `main`.

**Comment by stoobie** [comment]
Yes, it's great.

**Review by stoobie — APPROVED** [review]
LGTM

**Comment by stoobie** [comment]
@xiaolou86 Thank you for your contribution, you can see it live now! I sent you a reward on OnlyDust.

**Comment by xiaolou86** [comment]
@stoobie haha, thank you.

**Pull request merged**
